- name: 拷贝coredns必要依赖的docker镜像
  copy: src=coredns-v1.8.0.tgz dest='/tmp/' owner=root group=root

- name: 导入coredns到本地镜像库
  shell: docker load < /tmp/coredns-v1.8.0.tgz

- name: 拷贝dns.yaml文件
  template:
   dest: "/tmp"
   src: dns.yaml
  when: groups['Cert']|join(',')|search(inventory_hostname)

- name: 应用dns.yaml
  shell: '{{kubernetes_home}}/kubectl/bin/kubectl apply -f /tmp/dns.yaml'
  when: groups['Cert']|join(',')|search(inventory_hostname)